[build]
target = "./index.html"

[watch]
ignore = ["./src-tauri", "./style.css"]

[serve]
port = 1420
open = false

[[hooks]]
stage = "pre_build"
command = "stylance"
command_arguments = [".", "--output-file", "style.css"]
